atlassian/landkid

- src/hosts/BitbucketAdapter.js
- src/static/bitbucket/index.js
Small fix to misnamed qs variable, and adding a function to window.
Rest is just prettier im pretty sure
> Fixes small issue in front end with clicking land button

- server.js
- src/Client.js
- src/Runner.js
- src/index.js
- src/routes.js
- src/static/bitbucket/index.js
- src/types.js
All functionality there.
Just using a simple array to track them atm.
Definitely want to revisit the State in Runner at some point.
Added a bunch of TODO's around the place.
Only known but that I'll get to soon is that refreshing the page after clicking mergeWhenAble will show you that you are not in the queue.
In terms of testing, I'll need to do a bunch around making sure that duplicated webhooks and combinations of landRequests + mergeWhenAble requests don't lead to any weirdness
> Adds landWhenAble functionality

- .prettierrc
- package.json
- src/hosts/BitbucketAdapter.js
- test/bitbucket/test.js
- yarn.lock
I also finally fixed my prettier problems, so I'll slowly be fixing files as I touch them.
> Adds retrying when trying to merge

- package.json
- src/Client.js
- src/Runner.js
- src/ci/BitbucketPipelinesAdapter.js
- src/hosts/BitbucketAdapter.js
- src/routes.js
- src/static/current-state/components/CurrentState.js
- src/static/current-state/components/QueueItem.js
- src/static/current-state/components/Tabs.js
- src/types.js
Links to Pullrequest and builds, even before statusEvent is fired
> Adding more links to frontend

- src/hosts/BitbucketAdapter.js
*Temporary* fix whilst we investigate
> Makes the merge error logging much more prominent

- src/static/index.html
Don't look at it, just approve and merge.
> New landing page 🙌

- config.example.js
- src/bitbucket/BitbucketClient.ts
- src/lib/Runner.ts
- src/routes/bitbucket/proxy/index.ts
- src/static/current-state/components/App.tsx
- src/static/current-state/components/CurrentState.tsx
- src/static/current-state/components/Header.tsx
- src/static/current-state/components/Logo.tsx
- src/static/current-state/components/QueueItem.tsx
- src/static/current-state/components/RunningBuild.tsx
- src/static/current-state/components/WithAPIData.tsx
- src/static/current-state/components/tabs/HistoryTab.tsx
- src/static/current-state/components/tabs/SystemTab.tsx
- src/static/current-state/components/tabs/index.tsx
- src/types.ts
Important files are:
- config.example.js
- src/bitbucket/BitbucketClient.ts
- src/lib/Runner.ts
- src/routes/bitbucket/proxy/index.ts
- src/types.ts
Everything else is just me changing some components into arrow functions for consistency's sake.
> Custom Pull Request checks/rules

- src/lib/Runner.ts
- src/routes/api/index.ts
- src/static/current-state/components/tabs/HistoryTab.tsx
- src/static/current-state/components/tabs/QueueTab.tsx
- src/static/current-state/components/tabs/index.tsx
Also displays message on Queue and History tabs "Contact an admin for permission to view this information".
> Don't send any build info (Queue + History) if the user is below Land permission

- src/bitbucket/BitbucketClient.ts
- src/routes/bitbucket/proxy/index.ts
- src/static/bitbucket/components/App.tsx
- src/types.ts
Added new category of custom rules, are displayed on the landkid PR view if they fail but will not prevent landing.
Also allow use of axios in custom rules.
> Custom Warnings + Allow use of Axios in custom rules

- src/bitbucket/BitbucketClient.ts
- src/bitbucket/BitbucketPipelinesAPI.ts
- src/lib/Runner.ts
https://product-fabric.atlassian.net/browse/AFP-1334
Tested here: https://bitbucket.org/jackrgardner/atlassian-frontend-landkid-test-repo/addon/pipelines/home#!/results/1841
> Pass target branch as variable to build

- .circleci/config.yml
- cypress.json
- cypress/integration/double-reentry.spec.js
- cypress/integration/utils/index.js
- package.json
- src/bitbucket/BitbucketAPI.ts
- src/bitbucket/BitbucketClient.ts
- src/bitbucket/BitbucketPipelinesAPI.ts
- src/lib/Runner.ts
- src/lib/utils/locker.ts
- src/static/bitbucket/components/App.tsx
Action items from https://hello.atlassian.net/wiki/spaces/~904291390/pages/767240910/Weirdness
> More logging

- src/bitbucket/BitbucketAPI.ts
- src/bitbucket/types.d.ts
https://product-fabric.atlassian.net/browse/AFP-2402
> Add authentication and typing to polling merge status

- config.example.js
- docker-compose.yml
- package.json
- src/index.ts
- src/lib/Runner.ts
- src/lib/Stats.ts
- src/lib/utils/stats.ts
- src/routes/api/index.ts
- src/routes/bitbucket/proxy/index.ts
- src/types.ts
- yarn.lock
Added custom data metrics for:
- on startup
- pull request landed / queued / queued when able
- user gets the current state
> Afp 2658 - Adding custom data metrics

- package.json
- yarn.lock
Will test by deploying to dev, but building works fine with no issues.
> resolve ua-parser-js to 0.7.24

- package.json
- yarn.lock
https://sca.analysiscenter.veracode.com/vulnerability-database/vulnerabilities/27848
> Bump axios to ^0.21.1

- Dockerfile
This just updates system deps to close out some vuln's
> Afp 3075 Update system deps

- config.example.js
- webpack.config.js
This PR adds `SERVER_PORT` and `DEV_SERVER_PORT` variables to allow starting the server on different ports
> Allow starting on different ports

- src/bitbucket/descriptor.ts
- src/static/bitbucket/components/App.tsx
- src/static/bitbucket/index.html
> Display more verbose error with instructions when user denies access to the addon

- package.json
- yarn.lock
Hey,
Bumping Axios to 0.21.4 to fix the ReDoS issue -> https://asecurityteam.atlassian.net/browse/VULN-571516
https://github.com/axios/axios/issues/3979
> Bump Axios to 0.21.4 to fix ReDoS

- src/bitbucket/BitbucketAPI.ts
- src/bitbucket/types.d.ts
- tests/unit/BitbucketAPI.test.ts
> Revert "add workaround for getting task count"

- src/bitbucket/BitbucketAPI.ts
- src/bitbucket/types.d.ts
- tests/unit/BitbucketAPI.test.ts
@diffidentDude raised this PR originally https://github.com/atlassian/landkid/pull/136 and it was not possible to run the CI as he was not added yet as a contributor.
I am recreating the PR to be able to run the CI
> Add workaround for getting task count

- src/lib/Queue.ts
only fetch requests from last 7 days
> WIP AFP-3330 only fetch requests from last 7 days

- .github/workflows/docker.yml
re-deploy landkid to fix vulns
> re-deploy landkid

- package.json
- src/routes/index.ts
- yarn.lock
> Add cache control headers to static requests

- src/bitbucket/BitbucketAPI.ts
- src/lib/Runner.ts
- tests/unit/BitbucketAPI.test.ts
> Include failure reason when possible when a merge fails

- src/bitbucket/BitbucketAPI.ts
- src/bitbucket/BitbucketClient.ts
- src/bitbucket/descriptor.ts
- src/bitbucket/types.d.ts
- src/lib/Runner.ts
- src/routes/bitbucket/proxy/index.ts
Adds a new land check — pull requests that are conflicted aren't landable.
> Add merge check for when there are conflicts

- src/db/migrations/08__mergeStrategyColumn.ts
Faced a similar issue like - https://github.com/sequelize/sequelize/issues/2554 when deploying changes in dev.
Switched to direct query.
Tested in local and it works fine.
Will test the script again in dev and staging before deploying to prod.
> Fix migration script

- config.example.js
- src/static/bitbucket/components/App.tsx
- src/static/bitbucket/components/Message.tsx
- src/static/bitbucket/utils/getWidgetSettings.ts
- src/types.ts
Wrapping the squash merge feature behind FF
> Wrap squash merge behind ff

- src/db/__mocks__/index.ts
- src/db/index.ts
- src/lib/StateService.ts
- src/lib/__mocks__/StateService.ts
- src/lib/__tests__/Runner.test.ts
- src/lib/__tests__/StateService.test.ts
- src/routes/api/index.ts
- src/routes/api/test.ts
- src/types.ts
- typings/ambient.d.ts
https://hello.atlassian.net/browse/MONO-329
- Add new `PriorityBranch` table to DB
- Add new table CRUD operations 
- Unit tests
- Add `/add-priority-branch` and `/remove-priority-branch` API routes
UI component for this feature to be implemented in a separate PR
> MONO-329 Land priority branch add service logic

- package.json
- src/lib/Runner.ts
- src/lib/StateService.ts
- src/lib/__mocks__/StateService.ts
- src/lib/__tests__/Runner.test.ts
- src/lib/__tests__/StateService.test.ts
- src/lib/utils/__tests__/helper-function.test.ts
- src/lib/utils/helper-functions.ts
- src/routes/api/index.ts
- src/routes/bitbucket/proxy/index.ts
- src/static/current-state/components/App.tsx
- src/static/current-state/components/InlineEdit.tsx
- src/static/current-state/components/QueueItem.tsx
- src/static/current-state/components/tabs/PriorityBranchList.tsx
- src/static/current-state/components/tabs/SystemTab.tsx
- src/static/current-state/components/tabs/index.tsx
- typings/ambient.d.ts
- yarn.lock
Added priority branch UI to admin controls
- Priority branches can be added, edited, removed
- Duplication check on edit/add
Example use where `test-priority/*` has been added to the priority branch list (priority has been bumped for priority branch)
**Test plan**
- added unit tests
- integration tests to be added in the `atlassian-frontend-landkid-deployment` repo 
- tested against scenarios where multiple priority branches are in the queue - the priority will be given to the priority branch queued first (I think this is fine but we could possibly look at "ordering" the priority in the future)
> MONO-301 Land priority branch UI implementation

- src/bitbucket/BitbucketAPI.ts
- src/bitbucket/__mocks__/BitbucketAPI.ts
- src/bitbucket/__tests__/BitbucketAPI.test.ts
- src/db/__mocks__/index.ts
- src/lib/Runner.ts
- src/lib/StateService.ts
- src/lib/__mocks__/StateService.ts
- src/lib/__tests__/Runner.test.ts
- src/routes/api/index.ts
- src/routes/api/test.ts
- src/types.ts
Will retry failed merges twice in 15s intervals.
> Retry failed PR merges

- src/lib/Runner.ts
- src/lib/__tests__/Runner.test.ts
**Problem**
There are few instances of unexpected state transition. The newly introduced `checkRunningLandRequests` triggers `onStatusUpdate` operation. `onStatusUpdate` is also triggered via webhook when land build is completed. The race condition between this two operation causes this unexpected transition.
**Solution**
Updated `onStatusUpdate` operation to consider land request status which are in running state. Previously, `awaiting-merge` and `merging` statuses were also considered.
> Resolve unexpected land request state changes

- src/static/current-state/components/CurrentState.tsx
- src/static/current-state/components/RunningBuilds.tsx
- src/static/current-state/components/tabs/MergingTab.tsx
- src/static/current-state/components/tabs/index.tsx
- src/static/current-state/utils/LandRequestUtils.ts
Added `Merging` tab.
**Empty state**
**Queue contains requests**
> Added new merging tab.

- src/bitbucket/BitbucketAPI.ts
- src/bitbucket/__tests__/BitbucketAPI.test.ts
copied from https://bitbucket.org/atlassian/landkid/pull-requests/2
> Include PR title in merge commits
