atlassian/landkid

src/bitbucket/BitbucketAPI.ts

Because of gdpr released to 50% of user in Bitbucket, we needed to replace `username` by `account_id`

Possible fix for Landkid gdpr issue: replace username by account_id

---

src/routes/api/index.ts
src/routes/index.ts
src/types.ts

Adds a config option that is reflected on the `api/meta` endpoint.
This is useful when doing deployment tests and you need to be able to know if things are changing or not.

Adds easter egg config option for testing

---

src/bitbucket/BitbucketAPI.ts
src/bitbucket/types.d.ts

This takes a specific change from https://github.com/atlassian/landkid/pull/44 but branched off master before the parallel builds work so that we can deploy only this change.

Add status name to build statuses API response

---

src/lib/Runner.ts
src/routes/api/index.ts

I think this might fix the maxConcurrentBuilds issue as well

Check if running builds have any failed dependencies before adding them as a dep

---

package.json
src/auth/bitbucket.ts
src/bitbucket/BitbucketAPI.ts
src/bitbucket/BitbucketAuthenticator.ts
src/bitbucket/BitbucketClient.ts
src/bitbucket/BitbucketPipelinesAPI.ts
src/index.ts
src/lib/Config.ts
src/lib/Logger.ts
src/lib/PermissionService.ts
src/lib/Runner.ts
src/lib/utils/locker.ts
src/routes/api/index.ts
src/routes/auth/index.ts
src/routes/bitbucket/lifecycle/index.ts
src/routes/bitbucket/proxy/index.ts
src/routes/bitbucket/webhook/index.ts
src/routes/middleware.ts
yarn.lock

Added new `verbose` logging level for local development.
Added namespaces to all logs, which can be filtered with:
- locally with the `LOG_NAMESPACES` env var
- `LOG_NAMESPACES=routes:api:* yarn dev` will only shows logs from `src/routes/api`
- in splunk with `namespace` variable
- `namespace=routes:api:*`
Added basic indicators to as many logs as possible: `requestId`, `pullRequestId`, `buildId`, and similar. Allows these variables to be used in Splunk to follow the flow of requests, pull requests, builds, etc.

Improved Logging

---

package.json
yarn.lock

This updates lodash to 4.17.19 (in `yarn.lock` — it's depended on transitively) and cypress to ^4.11.0, which depends on a pinned version of lodash.
Test Plan: CI

Update lodash to 4.17.19 and cypress to ^4.11.0

---

src/lib/Runner.ts

`checkWaitingLandRequests` has a similar functionality to `next`, it iterates over a list of requests and performs status transition actions. We lock `next` so there are no conflicts, we should also do that here.
[see investigation here](https://hello.atlassian.net/wiki/spaces/~904291390/pages/767240910/Weirdness)

Add status-transition lock to checkWaitingLandRequests

---

src/bitbucket/BitbucketClient.ts
src/lib/Runner.ts
src/static/current-state/components/QueueItem.tsx

- Adds `Landed by:` field to queue items on the frontend
- Refactors status reason to use the user's `displayName` if it exists, and the `aaid` if it doesn't

AFP-2125 Landkid Blame

---

src/lib/Runner.ts
src/routes/api/index.ts

Adding /clear-land-when-able-queue API to avoid PR stalling in this queue.
We are getting some alarms (500x from the load balancer), investigating the issue, it seems coming from PRs that stall in the land-when-able-queue.
This PR adds an endpoint for admin to remove / abort PRs to the land-when-able-queue
* Deploy this change to dev / staging landkid environment
* Create a PR
* Land when able this PR
* Add a task to make sure the PR stays in this state
* Run the script with the new endpoint

Adding /clear-land-when-able-queue API 

---

src/bitbucket/BitbucketClient.ts
src/lib/Runner.ts
src/routes/bitbucket/proxy/index.ts

- changed `isAllowedToLand` -> `isAllowedToMerge`
- created new `isAllowedToLand` in the runner that calls `isAllowedToMerge` then does a check for an existing request
- Accepts a function that returns a list of land requests so that the existing request can be searched for in different queues

new IsAllowedToLand function that includes an existing request check

---

package.json
yarn.lock

https://sca.analysiscenter.veracode.com/vulnerability-database/vulnerabilities/29405
**Affected versions**: 0.1.0-4.17.20. 
**Patch:** https://github.com/lodash/lodash/commit/3469357cff396a26c363f8c1b5a91dde28ba4b1c  
**SourceClear** recommends updating to: 4.17.21 (or newer)

Resolve lodash to ^4.17.21 to fix vulnerability

---

package.json
src/static/current-state/components/QueueItem.tsx

* Moved the Pipelines Link into the card title.
* The pipe separator in the title is deliberately light to make it fade into the background since it doesn't need to be too prominent as a separator.
* Removed the [PR #] prefix and instead hyperlinked the PR title.
* Applied custom styling to the PR title to avoid double blue adjacent links
**Before:**
**After:**

Move pipeline link into card title. Link pr title instead of pr number

---

config.example.js
src/bitbucket/BitbucketAPI.ts
src/bitbucket/BitbucketClient.ts
src/lib/Runner.ts
src/types.ts
tests/unit/BitbucketAPI.test.ts

When set, merge commits for PRs will opt out of the destination branch
build via [skip ci] when there are successful dependent PRs awaiting
merge.
This prevents multiple destination branch builds from triggering when
PRs are landed in quick succession which can affect builds that update
src and push back to the repo such as publishing new versions of npm
libraries.

Add `skipBuildOnDependentsAwaitingMerge` config option

---

src/bitbucket/BitbucketAPI.ts
src/bitbucket/BitbucketClient.ts
src/bitbucket/descriptor.ts
src/db/index.ts
src/lib/AccountService.ts
src/lib/Runner.ts
src/lib/utils/locker.ts
src/static/current-state/components/Header.tsx
src/static/current-state/components/QueueItem.tsx
tests/integration/utils/index.ts
tests/unit/BitbucketAPI.test.ts
typings/ambient.d.ts

This avoids the issue where merging takes longer than the TTL of the `status-transition` lock which allows another merge attempt to be triggered, causing the land request to say "Unable to merge pull request" despite having successfully merged it.

New state for when a PR is in the process of merging

---

src/static/current-state/components/RunningBuilds.tsx

We should show them in the running section.

PRs that are merging disappear from the Landkid current-state view

---

package.json
src/db/index.ts
src/db/migrations/06__priorityColumn.ts
src/lib/Queue.ts
src/lib/Runner.ts
src/routes/api/index.ts
src/static/current-state/components/App.tsx
src/static/current-state/components/QueueItem.tsx
src/static/current-state/components/QueueItemsList.tsx
src/static/current-state/components/RunningBuilds.tsx
src/static/current-state/components/WithAPIData.tsx
src/static/current-state/components/tabs/HistoryTab.tsx
src/static/current-state/components/tabs/Messenger.tsx
src/static/current-state/components/tabs/QueueTab.tsx
src/static/current-state/components/tabs/SystemTab.tsx
src/static/current-state/components/tabs/index.tsx
typings/ambient.d.ts
yarn.lock

Just a simple numeric priority system, stored in the request table so it can persist between queue statuses if something re-queues due to a failed dependency.
Admins can increment and decrement based on the importance of a PR, and requests will be bumped every time they re-queue so that merge times are decreased for PRs unfairly effected by other PRs.

Land request priority system

---

src/static/current-state/components/QueueItem.tsx

Don't know how I didn't notice this but the button I was using to test the API was left in after I added in the real buttons.

Remove unnecessary increment priority button

---

Dockerfile
package.json
yarn.lock

Resolve path-parse to secure version and use `node:12-buster-slim` base image which uses `debian:10` instead of `debian:9`.

path-parse bump and use debian:10 base image

---

Dockerfile

Upgrades from Node `12.22.1` to `12.22.3` and pins it to that exact version for deterministic results on rebuilds

AFP-3081 Upgrade & pin node version at 12.22.3

---

src/bitbucket/BitbucketAPI.ts
src/bitbucket/types.d.ts
tests/unit/BitbucketAPI.test.ts

This change introduces a workaround for an issue where bitbucket returns a task_count of 0 when calling the pull_request API. We can instead directly call the /tasks endpoint, which returns the correct data.
This fix will unblock https://hello.atlassian.net/browse/EXPAND-1437
The bitbucket bug is tracked https://softwareteams.atlassian.net/browse/COREX-4320

add workaround for getting task count

---

src/db/index.ts
src/lib/PermissionService.ts

This needs to be combined with an update to the Landkid deployment repositories, so Landkid is deployed behind the VPN.

Give authenticated users land rights by default

---

src/lib/Runner.ts
tests/unit/Runner.test.ts

land requests won't move from queued to running when paused

when paused, disallow land requests to move to running

---

.storybook/main.js
.storybook/preview.js
package.json
src/bitbucket/BitbucketClient.ts
src/routes/bitbucket/proxy/index.ts
src/static/bitbucket/components/App.tsx
src/static/bitbucket/components/Errors.tsx
src/static/bitbucket/components/Message.stories.tsx
src/static/bitbucket/components/Message.tsx
src/static/bitbucket/components/Warnings.tsx
src/static/bitbucket/index.html
src/static/bitbucket/index.tsx
tsconfig.json
yarn.lock

**Theming adjustments to add-on to align styles closer with Atlassian Design System guidelines. This makes the add-on look like it belongs in Bitbucket.**
- Replaced UI with Atlassian Design System components
- Installed Storybook to improve add-on development experience. [Demo video here](https://www.loom.com/share/8a0b8ce13c2d4c77938a81061ab64405). Start using `yarn run storybook`
- Splits class component App.tsx into several smaller functional components. The separation makes it much easier to test in isolation, as Bitbucket is not required to develop the UI of the add-on
- Added loading states when performing actions "land" and "land when able". This provides feedback to the user that something is happening once they've clicked a button
- Added loading spinner while checking if able …

ShipIt 54: Add-on theming updates

---

src/static/bitbucket/components/Message.tsx
tsconfig.json

Fixes a bug where the home page opens within the Bitbucket addon iframe when clicking "Learn more about Landkid"
Also fixes a bug where Storybook files were being emitted. Thought this was fixed previously, but the pattern was incorrect.

External link fix

---

package.json
src/bitbucket/BitbucketAPI.ts
src/bitbucket/BitbucketAuthenticator.ts
src/bitbucket/BitbucketMerger.ts
src/bitbucket/BitbucketPipelinesAPI.ts
src/routes/middleware.ts
src/static/bitbucket/components/Message.stories.tsx
tests/integration/utils/index.ts
tsconfig.base.json
tsconfig.json
webpack.config.js
yarn.lock

Mainly fixes an issue I suspect caused server authentication failures in staging due to a default import mistake from `atlassian-jwt` in `middleware.ts`. I've converted all wildcard imports to be direct.
Also:
- Storybook was no longer loading the `Message` story because of an error with `@atlaskit/button@^16.3.6`. I think the error is related to a missing analytics context provider which is not being used in Landkid. I rolled back to `^15.0.0` before this was required to fix.
- Locked TypeScript version to match AF
- Fixed tsconfig for integration tests. Not sure these are used anyway?
- Updated Webpack devServer config after the Webpack 5 upgrade (does not affect production builds). Should be working again but I can't verify without a valid config.js

Server auth fixes

---

src/static/bitbucket/components/Message.tsx

Minor bugfix. Prevents the app authorizations page link opening inside the Landkid `<iframe>`, when user is denied access.

Open app authorizations page in new tab

---

Dockerfile

Enable docker layered caching to work for node_modules if package.json / yarn.lock are unmodified.

Enable layered caching of node_modules

---

package.json
src/bitbucket/descriptor.ts
src/lib/Runner.ts
src/routes/api/index.ts
src/routes/bitbucket/proxy/index.ts
src/static/bitbucket/components/App.tsx
src/static/bitbucket/components/Message.stories.tsx
src/static/bitbucket/components/Message.tsx
src/static/bitbucket/components/Queue.stories.tsx
src/static/bitbucket/components/Queue.tsx
src/static/bitbucket/components/types.ts
src/static/bitbucket/index.html
src/static/bitbucket/utils/RequestProxy.ts
yarn.lock

https://user-images.githubusercontent.com/8946207/189759073-5cf64efe-058f-4c52-8239-70773093ef4d.mp4
Render all reasons to browse to the queue page un-necessary with auto-updating queue statuses without ever needing to refresh the page.

Add polling and queue status to landkid widget

---

src/routes/bitbucket/proxy/index.ts

Land checks (especially ones that query an open PR) can fail due to the PR already being closed.

Dont run land checks if the PR merged or already merging

---

config.example.js
src/static/bitbucket/components/App.tsx
src/static/bitbucket/index.ejs
src/static/bitbucket/utils/getWidgetSettings.ts
src/types.ts
webpack.config.js

Don't auto refresh when not in view — previously we'd auto-refresh if the widget was not in the viewport, albeit at a much slower rate.

Cut down on auto-refresh

---

src/bitbucket/descriptor.ts
src/routes/bitbucket/proxy/index.ts
src/static/bitbucket/components/App.tsx
src/static/bitbucket/index.html
src/static/bitbucket/utils/getWidgetSettings.ts
webpack.config.js

My [previous attempt](https://github.com/atlassian/landkid/pull/181) to expose dynamic settings to the widget was un-successful. This is because `config.js` is essentially not used at build time (it is, but only for webpack dev server), and only powers the node server configuration.
Instead, I now fetch settings through a new server endpoint now. It is a bit of an overkill, but should allow us to set to tweak settings for the widget internally without needing to make and publish new landkid images in the future.

[Ready] Use an endpoint for widget settings

---

src/bitbucket/BitbucketAPI.ts

In case we cannot fetch diffstat for conflict checking, we'll assume that there were no conflicts — since it is possible for diffstat to fail when a PR has already been merged.

Not conflicting if we cannot process diffstat

---

src/static/bitbucket/components/App.tsx

Ideally given that I add a timeout to the daisy chain only after the previous one has expired, there shouldn't be timeouts running in parallel.  But I want to clear older timeouts here — just as a good practice and a remote chance that we had irregular re-renders setting up additional timeouts.

Clear timeouts before setting a new one

---

package.json
src/bitbucket/BitbucketAPI.ts
src/bitbucket/BitbucketMerger.ts
src/db/index.ts
src/db/migrations/08__mergeStrategyColumn.ts
src/lib/Runner.ts
src/routes/bitbucket/proxy/index.ts
src/static/bitbucket/components/App.tsx
src/static/bitbucket/components/Message.tsx
src/static/bitbucket/components/styles/checkboxStyles.ts
src/static/bitbucket/utils/RequestProxy.ts
src/types.ts
tests/unit/BitbucketAPI.test.ts
typings/ambient.d.ts
yarn.lock

This PR gives the users, ability to to squash merge the commits when landkid merges to master. 
We enable the checkbox by default. Unchecking will result in a usual merge commit.
1. Add a new column `mergeStrategy` to `LandRequest` table.
2. Pass the user selection to to both `/land-when-able` and `/land` endpoints.
3. Store the `mergeStrategy` value in the DB
4. When the task is ready for merge, read the value from the DB and use that in Bitbucket pipelines API to decide merge strategy.

Add squash merge feature

---

src/static/bitbucket/components/App.tsx
src/static/bitbucket/components/Message.tsx

Previously, we wouldn't show a land button when the PR was in "Queued for land" state. It was expected that the Landkid poller would anyways land the PR when ready.
But it turns out that we only look at land requests in the last 7 days for polling. This means its possible for a PR to go into a "stuck" state, where it becomes "landable" after 7 days, but is still in "Queued for land".
Now ideally, after 7 days, we should mark land requests in "Queued for land" back to the default state, so this problem of stuck PRs does not arise.
But as immediate mitigation, I'm adding back the land button to the "Queued for land" in case the PR is landable.
This will also allow you to skip the 2-minute poll time if you wish and land changes immediately.

Allow land button even when in queued state

---

src/bitbucket/BitbucketAPI.ts
src/bitbucket/__tests__/BitbucketAPI.test.ts
src/lib/Runner.ts
src/static/current-state/components/QueueItem.tsx

Adding on to improving the reason messaging for failed landkid attempts. 
When we get a "Unable to merge pull request" error, there are failed merge checks fields given in the error logs. Adding this to the reason could be useful for users to know.
For long reason messages that extend the width

Add merge checks error messages to reason

---

src/bitbucket/BitbucketAPI.ts
src/bitbucket/__tests__/BitbucketAPI.test.ts
src/bitbucket/types.d.ts
src/lib/Runner.ts
src/routes/bitbucket/proxy/index.ts

**What's changed ?**
- During landing request verify if the commit build statuses for `landkid-priority` metadata.
- Increment the priority of the PR based on `landkid-priority`.
**Verfication**
Verified the changes on test repo. Need to perform e2e testing of the flow.

MONO-24 Updated PR priority during land-request.

---

src/db/index.ts
src/lib/Runner.ts

These can be used to track how long each status transition takes as well as how long it has been since the request was originally queued.

Add duration fields to LAND_REQUEST.STATUS.CHANGED event

---

src/lib/Runner.ts

This guards against a missing destinationBranch preventing users from landing. This can occur with an outdated ac descriptor that has not specified the destination branch as a query parameter to the `can-land` endpoint.

Only check for changed target branch when destinationBranch is supplied

---

CONTRIBUTING.md
__mocks__/express.ts
jest.config.js
src/lib/__mocks__/AccountService.ts
src/lib/__mocks__/Runner.ts
src/lib/__tests__/Runner.test.ts
src/lib/utils/__mocks__/locker.ts
src/lib/utils/__mocks__/redis-client.ts
src/routes/api/index.ts
src/routes/api/test.ts
webpack.config.js

This PR adds a route to manually mark a land build as failed. This will be used to fail land requests as soon as a step in the land build has failed instead of waiting for the entire build to finish.
I also copied over the local development guide here since it was missing.

Add route to manually fail a land build

---

src/db/__mocks__/index.ts
src/db/index.ts
src/lib/PermissionService.ts
src/lib/Runner.ts
src/lib/StateService.ts
src/lib/__mocks__/PermissionService.ts
src/lib/__mocks__/Runner.ts
src/lib/__mocks__/StateService.ts
src/lib/__tests__/Runner.test.ts
src/lib/__tests__/StateService.test.ts
src/routes/api/index.ts
src/routes/api/test.ts
src/routes/bitbucket/proxy/index.ts
src/static/current-state/components/App.tsx
src/static/current-state/components/tabs/SystemTab.tsx
src/static/current-state/components/tabs/index.tsx
src/types.ts
typings/ambient.d.ts

Added admin capability to update concurrent build slots at runtime. New table `ConcurrentBuildState` was added.

Added admin capability to update concurrent build slots.

---

src/lib/StateService.ts
src/lib/__mocks__/StateService.ts
src/routes/api/index.ts
src/routes/api/test.ts

I've been running into flakey cypress tests when trying to integrate the changes from https://github.com/atlassian/landkid/pull/210 into atlassian-frontend.
Some of the flakiness relates to server state not being reset in between tests/test suites/test executions - especially if there is a failure.
I've made a couple of changes to help with this:
* New route to delete all priority branches
* Update to the recently added routes to return error status codes on failure. I noticed these were not awaiting the DB calls and always returning success.
I plan to update the cypress test code to these routes to reset server state where required.

New API route updates to assist with e2e tests

---

src/bitbucket/BitbucketAPI.ts
src/bitbucket/__mocks__/BitbucketAPI.ts
src/bitbucket/__tests__/BitbucketAPI.test.ts
src/bitbucket/types.d.ts
src/db/__mocks__/index.ts
src/db/index.ts
src/db/migrations/09__impactColumn.ts
src/lib/Runner.ts
src/routes/bitbucket/proxy/index.ts
src/static/current-state/components/QueueItem.tsx
typings/ambient.d.ts

- Add impact field to LandRequest
- Add new migration script to update new column
- Update unit tests
- Add impact field to QueueItem UI
- Used BBC APIs to create a build status commit with my own test repository 
e.g. used curl to send the API request:  `curl -u 'wfyzheng:<auth token>' --request POST --url "https://api.bitbucket.org/2.0/repositories/wfyzheng/test/commit/d3ffb5f5fe59dd62a0ee1278a0367079ad4c4c05/statuses/build" -H 'Content-Type: application/json' -d '{"name": "landkid-impact", "key": "landkid-impact","state": "SUCCESSFUL", "description": "42", "url": "www.google.com"}'`

Add impact field to LandRequest

---

config.example.js
src/db/index.ts
src/db/migrations/10__speculationEngineAdminSettings.ts
src/lib/Queue.ts
src/lib/Runner.ts
src/lib/SpeculationEngine.ts
src/lib/StateService.ts
src/lib/__mocks__/Config.ts
src/lib/__mocks__/StateService.ts
src/lib/__tests__/Runner.test.ts
src/lib/__tests__/SepculationEngine.test.ts
src/lib/__tests__/StateService.test.ts
src/routes/api/index.ts
src/routes/api/test.ts
src/routes/bitbucket/proxy/index.ts
src/static/current-state/components/tabs/SystemTab.tsx
src/static/current-state/components/tabs/index.tsx
src/types.ts
typings/ambient.d.ts

Added speculation engine to re-order PR based on impact. It is target repos's responsibility to provide impact of each PR using BBP build statuses. The engine attempts to re-order a land-request if
1. speculationEngineEnabled feature is enabled
2. available free running slots are at least 2
3. Position of current requests in the queue compared to number of slots.
for example if 2 slots are available consider re-ordering 1st request from the queue
if 3 slots are available consider re-ordering 1st and 2nd request from the queue
4. Size of queue is more than 1
5. Impact of the current request compared to the next (available slots - 1) number of requests in queue
The feature can be live toggled using below admin controls.
Impact retrieved and integrated for re-ordering.
Impact displayed on …

Integrate speculation engine with impact

---

README.md
src/db/index.ts
src/db/migrations/09__updateDependsOnColumn.ts
src/lib/Runner.ts
src/lib/__tests__/Runner.test.ts

PRs that transition to running with more than 7 dependencies (including both running and awaiting-merge) will cause a `SequelizeDatabaseError: value too long for type character varying(255)` sequelize error.
This is caused by  dependsOn column of a landRequest table exceeding the max string length of 255 characters. The dependsOn column contains each dependency landRequest ID (36 characters) separated by commas (1 column). So only `Math.floor(255/36) = 6` dependencies can fit in the column. This means 2 running requests + 4 PRs awaiting merge.
When the sequelize error occurs, neither the dependsOn or buildId fields are attached to the land request after its status is set to running. This then results in the request eventually timing out after 2 hours due to our landkid build timeout …

Fix issues when there are too many PR dependencies

---

config.example.js
src/bitbucket/BitbucketAPI.ts
src/lib/Runner.ts
src/lib/__tests__/Runner.test.ts
src/types.ts

Added landBuildTimeoutTime to system configuration. So, each instance can update the timeout based on their CI requirements. It defaults to 120 mins if not configured.

MONO-521 Added landBuildTimeoutTime to instance configuration

---

src/lib/Runner.ts
src/lib/__tests__/Runner.test.ts

Updated the BBC webhook callback utility to fail all dependent requests simultaneously. This would create more scenarios where multiple running slots are freed up, eventually causing the speculation engine to kick in for re-ordering pull requests based on impact.

[dev] Fail all dependents in one go.
